//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int IdCuenta { get; set; }
        public Nullable<int> NumeroCuenta { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdBanco { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
