//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> IdTipoPersonaFiscal { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> IdOcupacion { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuentas { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
        public virtual Pai Pai { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoPersonaFiscal TipoPersonaFiscal { get; set; }
    }
}
